version: 2
updates:
  - package-ecosystem: nuget
    directory: "/api"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: nuget
    directory: "/api.tests"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/terraform"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/services/tashkeel"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/web.tests"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
