# docker-compose --env-file ./docker-compose-default.env up
# builds all images with their respective lts tags

services:
  mongo:
    build: ./database
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  static:
    build: ./static
    ports:
      - 3010:3010
    restart: always
  services:
    build: ./services
    ports:
      - 3020:3020
    restart: always
  api:
    build: ./api
    ports:
      - 3030:3030
    environment:
      - API_TASHKEEL_URL=${API_TASHKEEL_URL}
      - API_MONGO_DB_URL=${API_MONGO_DB_URL}
    restart: always
    depends_on:
      - mongo
      - static
      - tashkeel
  web:
    build: ./web
    ports:
      - 3040:3040
    restart: always
    depends_on:
      - api

volumes:
  db-data:
  mongo-config: