version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: openarabic
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: realPassW0r!d
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  tashkeel:
    build: ./services/tashkeel
    ports:
      - 5002:5002
    restart: always


volumes:
  db-data:
  mongo-config:
