version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: openarabic
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: realPassW0r!d
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  static:
    build: ./static
    ports:
      - 3010:3010
    restart: always
  tashkeel:
    build: ./services/tashkeel
    ports:
      - 3020:3020
    restart: always
  api:
    build: ./api
    ports:
      - 3030:3030
    environment:
      - TASHKEEL_URL=http://tashkeel:3020
      - MONGO_DB_URL=mongodb://user:password@mongo:27017/openarabic
    restart: always
    depends_on:
      - mongo
      - static
      - tashkeel
  web:
    build: ./web
    ports:
      - 3040:3040
    restart: always
    depends_on:
      - api

volumes:
  db-data:
  mongo-config: