version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: openarabic
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: realPassW0r!d
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  tashkeel:
    build: ./services/tashkeel
    ports:
      - 5002:5002
    restart: always
  static:
    build: ./static
    ports:
      - 8080:80
    restart: always
  api:
    build: ./api
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_URL=mongodb://user:password@mongo:27017/openarabic
    restart: always
  web:
    build: ./web
    ports:
      - 3001:3001
    restart: always
volumes:
  db-data:
  mongo-config: