version: "3.8"

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
  web:
    image: web
    build:
      context: .
      dockerfile: ./web/Dockerfile
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
