#!/bin/bash
# ^ Note the above "shebang" line. This says "This is an executable shell script"
# Name this script "pre-commit" and place it in the ".git/hooks/" directory

# If any command fails, exit immediately with that command's exit status
set -eo pipefail

yarn --cwd ./api version minor
yarn --cwd ./web version minor
yarn --cwd ./static version minor
yarn --cwd ./mobile version minor

echo "Version updated"
