apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: MONGO_DB_URL
            - name: TASHKEEL_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: TASHKEEL_URL
          image: registry.digitalocean.com/openarabic/api:#{BUILD_ID}#
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: 1000m
          #   requests:
          #     memory: 200Mi
          #     cpu: 150m
          livenessProbe:
            httpGet:
              path: /
              port: 3030
            periodSeconds: 10
            initialDelaySeconds: 30
          name: api
          ports:
            - containerPort: 3030
      restartPolicy: Always
