
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.digitalocean.com/openarabic/api:#{BUILD_ID}#
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: API_MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: MONGO_DB_URL
            - name: API_TASHKEEL_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: TASHKEEL_URL
            - name: API_IMAGES_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: IMAGES_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: API_KEY
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 100Mi
              cpu: 25m
          livenessProbe:
            httpGet:
              path: /health
              port: 3030
            periodSeconds: 10
            initialDelaySeconds: 30
          ports:
            - containerPort: 3030
      restartPolicy: Always
