apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.digitalocean.com/openarabic/api:#{BUILD_ID}#
          volumeMounts:
            - name: google-cloud
              mountPath: /usr/src/app/
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: API_MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: MONGO_DB_URL
            - name: API_TASHKEEL_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: TASHKEEL_URL
            - name: API_IMAGES_URL
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: IMAGES_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: API_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: AWS_SECRET_ACCESS_KEY
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: GOOGLE_APPLICATION_CREDENTIALS
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 100Mi
              cpu: 25m
          livenessProbe:
            httpGet:
              path: /health
              port: 3030
            periodSeconds: 10
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3030
            periodSeconds: 10
            initialDelaySeconds: 30
          ports:
            - containerPort: 3030
      restartPolicy: Always
      volumes:
        - name: google-cloud
          secret:
            secretName: google-cloud
