apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: api
  namespace: openarabic
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  progressDeadlineSeconds: 60
  service:
    port: 3030
    targetPort: 3030
    gateways:
      - public-gateway
    hosts:
      - backend.openarabic.io
    trafficPolicy:
      tls:
        mode: DISABLE
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: 'gateway-error,connect-failure,refused-stream'
  analysis:
    interval: 10s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 95
        interval: 10s
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 10s
    webhooks:
      - name: load-test-canary
        url: http://loadtester.loadtester/
        timeout: 5s
        metadata:
          cmd: 'hey -z 1m -q 10 -n 10 -c 2 http://api-canary.openarabic:3030/readiness'
