apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static
  name: static
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - name: static
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: registry.digitalocean.com/openarabic/static:#{BUILD_ID}#
          volumeMounts:
            - name: static-storage
              mountPath: /data
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 50Mi
              cpu: 25m
          livenessProbe:
            httpGet:
              path: /
              port: 3010
            periodSeconds: 10
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3010
            periodSeconds: 10
            initialDelaySeconds: 30
          ports:
            - containerPort: 3010
      restartPolicy: Always
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage
