apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-storage
  labels:
    type: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  readOnly: false
  allowVolumeExpansion: true
  
