apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: registry.digitalocean.com/openarabic/web:#{BUILD_ID}#
          ports:
            - containerPort: 3040
          resources:
            limits:
              memory: 512Mi
              cpu: 512m
            requests:
              memory: 50Mi
              cpu: 25m
          livenessProbe:
            httpGet:
              path: /
              port: 3040
            periodSeconds: 10
            initialDelaySeconds: 30
      restartPolicy: Always
