apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: registry.digitalocean.com/openarabic/web:#{BUILD_ID}#
          name: web
          ports:
            - containerPort: 3040
          resources:
            limits:
              memory: 1024Mi
              cpu: 1000m
            requests:
              memory: 50Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /
              port: 3040
            periodSeconds: 10
            initialDelaySeconds: 30
      restartPolicy: Always
