apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: web
  namespace: openarabic
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  progressDeadlineSeconds: 60
  service:
    port: 3040
    targetPort: 3040
    gateways:
      - public-gateway
    hosts:
      - web.openarabic.io
    trafficPolicy:
      tls:
        mode: DISABLE
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: 'gateway-error,connect-failure,refused-stream'
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 95
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
    webhooks:
      - name: load-test-canary
        url: http://loadtester.loadtester/
        timeout: 5s
        metadata:
          cmd: 'hey -z 1m -q 10 -c 2 http://web-canary.openarabic:3040/'
