apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "3040"
      port: 3040
      targetPort: 3040
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
