apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: #{API_TAG}#
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 50Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
          env:
            - name: ASPNETCORE_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: ASPNETCORE_AUTHORITY
            - name: ASPNETCORE_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: ASPNETCORE_AUDIENCE
            - name: ASPNETCORE_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: ASPNETCORE_ORIGINS
            - name: ASPNETCORE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: ASPNETCORE_CONNECTION_STRING
            - name: ASPNETCORE_SENDGRID_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: ASPNETCORE_SENDGRID_KEY
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 80
  selector:
    app: api
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.openarabic.io
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: api
              servicePort: 8090
