apiVersion: batch/v1
kind: Job
metadata:
  name: backup-database
spec:
  template:
    spec:
      containers:
        - name: backup-database
          image: mcr.microsoft.com/mssql-tools
          command:
            [
              "/opt/mssql-tools/bin/sqlcmd",
              "-S database",
              "-Usa",
              "-Prvv32DEWwaAqe23e32fr",
              "-q SELECT @@VERSION;",
            ]
      restartPolicy: Never
  backoffLimit: 4
