apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            limits:
              memory: 1000Mi
              cpu: "1"
            requests:
              memory: 700Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              host: /
              port: 80
            periodSeconds: 10
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: SA_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - name: volume
              mountPath: "/var/opt/mssql"
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: database-azurefile
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: NodePort
  ports:
    - port: 1433
      protocol: TCP
      targetPort: 1433
  selector:
    app: database
