apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            limits:
              memory: 1024Mi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 100m
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: SA_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - name: mssql
              mountPath: "/var/opt/mssql"
            - name: backup
              mountPath: "/var/opt/backup"
      volumes:
        - name: mssql
          persistentVolumeClaim:
            claimName: database-azurefile
        - name: backup
          persistentVolumeClaim:
            claimName: database-azurefile-backup
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: NodePort
  ports:
    - port: 1433
      protocol: TCP
      targetPort: 1433
  selector:
    app: database
