apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: tashkeel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tashkeel
  template:
    metadata:
      labels:
        app: tashkeel
    spec:
      containers:
        - name: tashkeel
          image: #{TASHKEEL_TAG}#
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 50Mi
              cpu: 100m
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tashkeel
  labels:
    app: tashkeel
spec:
  type: NodePort
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 80
  selector:
    app: tashkeel
