import { createAction } from '@reduxjs/toolkit'

export const RESET_TEXT = createAction('RESET_TEXT')
export const RESET_WORDS = createAction('RESET_WORDS')
export const SET_ARABIC_FONT_NAME = createAction('SET_ARABIC_FONT_NAME')
export const SET_ARABIC_FONT_SIZE = createAction('SET_ARABIC_FONT_SIZE')
export const SET_CATEGORIES = createAction('SET_CATEGORIES')
export const SET_ENGLISH_FONT_SIZE = createAction('SET_ENGLISH_FONT_SIZE')
export const SET_PRACTICING_WORDS = createAction('SET_PRACTICING_WORDS')
export const SET_TEXT = createAction('SET_TEXT')
export const SET_TEXT_LOADED = createAction('SET_TEXT_LOADED')
export const SET_TEXTS = createAction('SET_TEXTS')
export const SET_TEXTS_LOADED = createAction('SET_TEXTS_LOADED')
export const SET_TRANSLITERATION = createAction('SET_TRANSLITERATION')
export const SET_WORDS = createAction('SET_WORDS')
