export const GET_TITLE = 'GET_TITLE'
export const SET_TITLE = 'SET_TITLE'

export const GET_CATEGORY = 'GET_CATEGORY'
export const SET_CATEGORY = 'SET_CATEGORY'

export const GET_AUTHOR = 'GET_AUTHOR'
export const SET_AUTHOR = 'SET_AUTHOR'

export const GET_SOURCE = 'GET_SOURCE'
export const SET_SOURCE = 'SET_SOURCE'

export const GET_ENGLISH_TEXT = 'GET_ENGLISH_TEXT'
export const SET_ENGLISH_TEXT = 'SET_ENGLISH_TEXT'

export const GET_ARABIC_TEXT = 'GET_ARABIC_TEXT'
export const SET_ARABIC_TEXT = 'SET_ARABIC_TEXT'

export const GET_ARABIC_SENTENCE = 'GET_ARABIC_SENTENCE'
export const SET_ARABIC_SENTENCE = 'SET_ARABIC_SENTENCE'

export const GET_ENGLISH_SENTENCE = 'GET_ENGLISH_SENTENCE'
export const SET_ENGLISH_SENTENCE = 'SET_ENGLISH_SENTENCE'

export const GET_ARABIC_WORDS = 'GET_ARABIC_WORDS'
export const SET_ARABIC_WORDS = 'SET_ARABIC_WORDS'

export const GET_ENGLISH_WORDS = 'GET_ENGLISH_WORDS'
export const SET_ENGLISH_WORDS = 'SET_ENGLISH_WORDS'

export const GET_WORD_BY_WORD = 'GET_WORD_BY_WORD'
export const SET_WORD_BY_WORD = 'SET_WORD_BY_WORD'

export const GET_TEXT = 'GET_TEXT'
export const SET_TEXT = 'SET_TEXT'
