import { createAction } from '@reduxjs/toolkit'

export const RESET_TEXT = createAction('text/RESET_TEXT')
export const SET_ARABIC_SENTENCE = createAction('text/SET_ARABIC_SENTENCE')
export const SET_ARABIC_TEXT = createAction('text/SET_ARABIC_TEXT')
export const SET_ARABIC_WORDS = createAction('text/SET_ARABIC_WORDS')
export const SET_AUTHOR = createAction('text/SET_AUTHOR')
export const SET_CATEGORY = createAction('text/SET_CATEGORY')
export const SET_ENGLISH_SENTENCE = createAction('text/SET_ENGLISH_SENTENCE')
export const SET_ENGLISH_TEXT = createAction('text/SET_ENGLISH_TEXT')
export const SET_ENGLISH_WORDS = createAction('text/SET_ENGLISH_WORDS')
export const SET_IMAGE = createAction('text/SET_IMAGE')
export const SET_PUBLISH_AT = createAction('text/SET_PUBLISH_AT')
export const SET_SENTENCES = createAction('text/SET_SENTENCES')
export const SET_SOURCE = createAction('text/SET_SOURCE')
export const SET_STATUS = createAction('text/SET_STATUS')
export const SET_TEXT = createAction('text/SET_TEXT')
export const SET_TITLE = createAction('text/SET_TITLE')
export const SET_WORD_BY_WORD = createAction('text/SET_WORD_BY_WORD')
export const UPDATE_SENTENCE = createAction('text/UPDATE_SENTENCE')
