apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: database-azurefile
  resources:
    requests:
      storage: 5Gi
