POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "yunus",
    "age": "42"
}
###

GET http://localhost:3000/users HTTP/1.1
###

GET http://localhost:3000/users/62518818661588692cdb0d65 HTTP/1.1
###

PUT http://localhost:3000/users/62518818661588692cdb0d65 HTTP/1.1
content-type: application/json

{
    "name": "yunus",
    "age": "43"
}
###

DELETE http://localhost:3000/users/62518818661588692cdb0d65 HTTP/1.1
###



