apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api-deployment.yaml
- db-data-persistentvolumeclaim.yaml
- mongo-config-persistentvolumeclaim.yaml
- mongo-deployment.yaml
- static-deployment.yaml
- tashkeel-deployment.yaml
- web-deployment.yaml
