apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static
  name: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  strategy: {}
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - image: static
          name: static
          ports:
            - containerPort: 3010
          resources: {}
      restartPolicy: Always
