apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: docker.io/therealedenmind/oa-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: api
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  spec:
    rules:
      - host: api.openarabic.io
        http:
          paths:
            - path: /
              backend:
                serviceName: api
                servicePort: 8090
