name: Build, Push and Deploy OpenArabic

env:
  REGISTRY_NAME: registry.digitalocean.com/edenmind-oci-repository

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push API to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./api/Dockerfile
          tags: therealedenmind/oa-api:${{ github.sha }}
          context: ./api
          push: true

      - name: Build and Push Tashkeel to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./services/tashkeel/Dockerfile
          tags: therealedenmind/oa-tashkeel:${{ github.sha }}
          context: ./services/tashkeel/
          push: true

      - name: Build and Push Web to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./web/Dockerfile
          tags: therealedenmind/oa-web:${{ github.sha }}
          context: ./web
          push: true
