name: Build, Push and Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chek out source
        uses: actions/checkout@v2     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}    
      - name: Build and push API
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./api/Dockerfile
          tags: therealedenmind/oa-api:latest
          context: ./api
          push: true
      - name: Build and push Frontend
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./frontend/Dockerfile
          tags: therealedenmind/oa-frontend:latest
          context: ./frontend
          push: true
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Set target AKS cluster 
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: edenmind-aks
          resource-group: edenmind-aks-resources
