name: Build and Push

env:
  REGISTRY_NAME: docker.io/therealedenmind/
  CLUSTER_NAME: edenmind-aks
  CLUSTER_RESOURCE_GROUP: edenmind-aks-resources

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chek out source
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push API
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./api/Dockerfile
          tags: therealedenmind/oa-api:${{ github.sha }}
          context: ./api
          push: true
      - name: Build and push Frontend
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./frontend/Dockerfile
          tags: therealedenmind/oa-frontend:${{ github.sha }}
          context: ./frontend
          push: true
      - name: Set target AKS cluster
        uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - name: Deploy API and Frontend to AKS
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            ./iac/frontend.yaml
            ./iac/api.yaml
          images: |
            ${{ env.REGISTRY_NAME }}/oa-frontend:${{ github.sha }}
            ${{ env.REGISTRY_NAME }}/oa-api:${{ github.sha }}
