# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: SonarQube scan API
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: ./api
      
      - name: SonarQube scan Frontend
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: ./frontend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: therealedenmind
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
              
      - name: Build and push API
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./api/Dockerfile
          tags: therealedenmind/oa-api:latest
          context: ./api
          push: true
        
      - name: Build and push Frontend
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./frontend/Dockerfile
          tags: therealedenmind/oa-frontend:latest
          context: ./frontend
          push: true
          
