name: pr-compliance
on:
  pull_request_target:
    types: [opened, edited, reopened]

permissions:
  pull-requests: write

jobs:
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@v1.1.0

        with:
          ignore-team-members: false
          watch-files: |
            mobile/package.json
            api/package.json
            static/package.json
            web/package.json
