name: PR Compliance
on:
  push:
    branches-ignore: [main]

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

jobs:
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          protected-branch: "main"
          watch-files: |
            ./mobile/package.json
