name: Scan Repository with Snyke
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Snyk
        uses: snyk/actions@0.3.0
        with:
          command: test
          args: --all-projects --detection-depth=4 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
