name: Container Security Scan
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Snyk
        uses: snyk/actions/node@master
        with:
          command: test
          args: --all-projects --detection-depth=4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
